config/routes.rb
VideoCloud::Application.routes.draw do
  
  devise_for :users
  
  post "posts/new" => "posts#create"
  match "posts/paginate" => "posts#paginate"
  
  resources :users
  resources :posts
  
  root :to => "posts#new"
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_one :user
  has_one :icon
  
  scope :by_user_id, (lambda do |user_id|
    where("user_id = ?", user_id).order("created_at DESC") unless user_id.blank?
  end)
    
  scope :by_user, (lambda do |user|
    where("user_id = ?", user.id).order("created_at DESC") unless user.blank?
  end)
  
  scope :by_month, (lambda do |month|
    where("extract(month from created_at) = ?", month) unless month.blank?
  end)
  
  scope :by_date, (lambda do |year, month, day|
    where("extract(year from created_at) = ? AND extract(month from created_at) = ? AND extract(day from created_at) = ?", year, month, day)
  end)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nickname
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    unless session[:new_post].blank?
      new_post_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    # if user was composing a new post before logging in
    # show the post
    unless session[:new_post].blank?
      @status = "Please click Post when you are ready to post the letter"
      @asshole_name = session[:new_post][:asshole_name]
      @content = session[:new_post][:content]
      session[:new_post] = nil
    end
  end
  
  def index
    @page_size = 4
    @posts = Post.last(@page_size).reverse
    respond_to do |format|
      format.html
    end
  end
  
  # 
  def paginate
    by_user_id = params[:user_id]
    page_size = params[:page_size]
    to_page = params[:to_page]
    
    render :text => "missing page_size" and return if page_size.blank?
    render :text => "missing to_page" and return if to_page.blank?
    
    page_size = page_size.to_i
    to_page = to_page.to_i
    
    render :text => "page_size must be greater than 0" and return if page_size <= 0
    render :text => "to_page must be greater than 0" and return if to_page <= 0
    
    to_page -= 1 # starts with 0 index
    
    @posts = Post.by_user_id(by_user_id).order("created_at DESC").offset(page_size * to_page).limit(page_size).all
    
    render :json => [] if @posts.blank?
    
    # reformat posts
    @formatted_posts = []
    max_content_length = 300
    @posts.each do |p|
      post = {
        :asshole_name => p.asshole_name,
        :content => p.content.length > max_content_length ? p.content.truncate(300) : p.content,
        :continue => p.content.length > max_content_length,
        :created_at => p.created_at.strftime("%b %d, %Y"),
        :post_path => post_path(p.id),
        :user_name => User.find(p.user_id).nickname,
        :user_path => user_path(User.find(p.user_id))
      }
      @formatted_posts.push post
    end
    render :json => @formatted_posts unless @formatted_posts.blank?
  end
  
  def show
    @post = Post.find(params[:id])
    @user_owns_page = !current_user.blank? ? @post.user_id == current_user.id : false
    respond_to do |format|
      format.html
      format.json { render :json => @post }
    end
  end
  
  def create
    render :text => "params is blank!" and return if params[:post].blank?
    asshole_name = params[:post][:asshole_name]
    content = params[:post][:content]
    render :text => "either asshole's name or letter's content is blank!" and return if asshole_name.blank? || content.blank?
    
    if current_user.blank? # if not logged in
      session[:new_post] = {
        :asshole_name => params[:post][:asshole_name], 
        :content => params[:post][:content]
      }
      
      redirect_to "/users/sign_in" and return
    end
    render :text => "please login before writting a letter to an asshole" and return if current_user.blank?
    
    data = params[:post]
    data.merge!({
      :user_id => current_user.id,
      :content => content,
      :asshole_name => asshole_name
    })
    
    @post = Post.create(data)
    if @post.save
      flash[:notice] = "Congrats! Your letter to the asshole has been saved!"
      redirect_to user_path(current_user.id)
    else
      respond_to do |format|
        flash[:error] = "Something went wrong while saving your letter"
        format.html { render :action => "new" }
      end
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    render :text => "error: blank params" and return if params[:post].blank?
    @post = Post.find(params[:post][:id])
    if @post.update_attributes params[:post]
      flash[:notice] = "Your changes to the  letter has been saved!"
      redirect_to user_path(current_user.id)
    else
      respond_to do |format|
        flash[:error] = "Something went wrong while saving your letter"
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    render :text => "error: blank id" and return if params[:id].blank?
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Your letter to the asshole has been deleted... why did you do that??"
    else
      flash[:error] = "Something went wrong while saving your letter"
    end
    redirect_to user_path(current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render :text => "Wrong place to be..."
  end
  
  def show
    @page_size = 4
    @user = User.find(params[:id])
    @posts = Post.by_user_id(@user.id).first(@page_size)
    render :text => "User has no post" and return if @posts.blank?
    @user_owns_page = !current_user.blank? && @user.id == current_user.id
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dear asshole,</title>
  <%= javascript_include_tag :defaults, "/javascripts/jquery.blockUI.js", "/javascripts/jquery.rating.js" %>
  <%= stylesheet_link_tag :all, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
      <ul class="nav">
        <li>
          <div class="logo">
            <%= link_to posts_path do %>
              <h1>Dear Asshole</h1>
            <% end %>
          </div>
        </li>
        <li>
          <%= link_to "Encountered new asshole today?", new_post_path %>
        </li>
        <%
        if current_user.blank?
        %>
          <li>
          <%= link_to "Log in", "/users/sign_in" %>
          </li>
          <li>
          <%= link_to "Sign up", "/users/sign_up" %>
          </li>
        <%
        else
        %>
          <li>
          <%= link_to "Hey #{current_user.nickname}.", user_path(current_user) %>
          </li>
          <li>
          <%= link_to "Log out", "/users/sign_out" %>
          </li>
        <%
        end
        %>
        <li>
          <h4 style="padding: 9px 0px 0px 25px">So many assholes, so little time...</h4>
        </li>
      </ul>
      </div>
    </div>
  </div>
  <p class="notice flash"><%= flash[:notice] %></p>
  <p class="error flash"><%= flash[:error] %></p>
  
  <div id="main-content">
    <%= yield %>
  </div>
  
  <script type="text/javascript">
    <%
    unless current_user.blank?
    %>
    window.currentUser = {
      id : "<%= current_user.id %>",
      email: "<%= current_user.email %>"
    }
    <% end %>
  </script>
  
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36543033-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</body>
</html>

app/views/posts/edit.html.erb
<div class="new-post-box">
  <%= form_for @post do |f| %>
  <span>Dear asshole </span>
  <input id="asshole-name" name="post[asshole_name]" type="text" value="<%= @post.asshole_name%>"></input>
  <span>,</span>
  <input type="hidden" name="post[id]" value="<%= @post.id %>"></input>
  <textarea name="post[content]" cols="0" rows="5"><%= @post.content %></textarea>
  <button class="btn btn-large">Post</button>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= javascript_include_tag "/javascripts/masonry.min.js" %>

<div id="quote">
  "Based on true stories"
</div>

<div id="front-page-post-wrapper">
  <% @posts.each do |p| %>
    <div class="content">
      <div class="user"><%= link_to User.find(p.user_id).nickname, user_path(User.find(p.user_id)) %></div>
      <div class="post-date">
      <%= p.created_at.strftime("%b %d, %Y") %>
      </div>
      <div class="body">
        Dear Asshole <%= p.asshole_name %>, 
        <br/>
        <% if p.content.length > 300 %>
        <%= truncate(p.content, :length => 300, :separator => " ") %>
        <%= link_to "(continue)", post_path(p.id) %>
        <% else %>
          <%= p.content %>
        <% end %>
      </div>
      <% if @user_owns_page %>
      <div class="controls">
        <%= link_to "Edit", edit_post_path(p.id) %>
        <%= link_to "Delete", post_path(p.id), :method => :delete, :confirm => "Are you sure you want to delete this letter??" %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="older-post">
  <a onclick="javascript: loadMore()">Older posts...</a>
</div>

<script type="text/javascript">
  // global toPage count
  var toPage = 1;
  var pageSize = <%= @page_size %>;
  
  window.onload = function() {
    var wall = new Masonry( document.getElementById('front-page-post-wrapper'), {
      columnWidth: 230
    });
  };
  
  function loadMore() {
    toPage++;
    
    $.ajax({
      method: "GET",
      url: "/posts/paginate?page_size=" + pageSize + "&to_page=" + toPage,
      success: function(data) {
        for(var i = 0; i < data.length; i++) {
          var post = data[i];
          var continueContent = post.continue ? "<a href='" + post.post_path + "'>(continue)</a>" : "";
          $("#front-page-post-wrapper").append("<div class='content'>\
          <div class='user'><a href='" + post.user_path + "'>" + post.user_name + "</a></div>\
          <div class='post-date'>\
          " + post.created_at + "\
          </div>\
          <div class='body'>\
            Dear Asshole " +  post.asshole_name + ", \
            <br>\
            " + post.content + " \
            " + continueContent + "\
          </div>\
        </div>");
        }
        var wall = new Masonry( document.getElementById('front-page-post-wrapper'), {
          columnWidth: 230
        });
      }
    })
  }
</script>

app/views/posts/new.html.erb
<div class="new-post-box">
  <div class="status">
    <%= @status %>
  </div>
  <%= form_for :post do |f| %>
  <span>Dear asshole </span>
  <input id="asshole-name" name="post[asshole_name]" type="text" placeholder="who (boss, dentist, tail-gater, land lord...)" value="<%= @asshole_name.blank? ? '' : @asshole_name %>"></input>
  <span>,</span>
  <textarea name="post[content]" cols="0" rows="5"><%= @content.blank? ? '' : @content %></textarea>
  <button class="btn btn-large">Post</button>
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post-wrapper">
  <div class="content">
    <%= @post.created_at.strftime("%b %d, %Y") %>
    <br/>
    Dear Asshole <%= @post.asshole_name %>, 
    <br/>
    <%= @post.content %>
    
    <% if @user_owns_page %>
    <div class="controls">
      <%= link_to "Edit", edit_post_path(@post.id) %>
      <%= link_to "Delete", post_path(@post.id), :method => :delete, :confirm => "Are you sure you want to delete this letter??" %>
    </div>
    <% end %>
    
  </div>
</div>

app/views/users/show.html.erb
<div id="post-wrapper">
  <% @posts.each do |p| %>
    <div class="content">
      <div class="post-date">
      <%= p.created_at.strftime("%b %d, %Y") %>
      </div>
      <div class="body">
        Dear Asshole <%= p.asshole_name %>, 
        <br/>
        <%= p.content %>
      </div>
      <% if @user_owns_page %>
      <div class="controls">
        <%= link_to "Edit", edit_post_path(p.id) %>
        <%= link_to "Delete", post_path(p.id), :method => :delete, :confirm => "Are you sure you want to delete this letter??" %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="older-post">
  <a onclick="javascript: loadMore()">Older posts...</a>
</div>

<script type="text/javascript">
  // global toPage count
  var toPage = 1;
  var pageSize = <%= @page_size %>;
  var userId = <%= !@current_user.blank? ? @current_user.id : "" %>;
  
  function loadMore() {
    toPage++;
    
    $.ajax({
      method: "GET",
      url: "/posts/paginate?page_size=" + pageSize + "&to_page=" + toPage + "&user_id=" + userId,
      success: function(data) {
        for(var i = 0; i < data.length; i++) {
          var post = data[i];
          $("#post-wrapper").append("<div class='content'>\
          <div class='user'><a href='" + post.user_path + "'>" + post.user_name + "</a></div>\
          <div class='post-date'>\
          " + post.created_at + "\
          </div>\
          <div class='body'>\
            Dear Asshole " +  post.asshole_name + ", \
            <br>\
            " + post.content + " \
          </div>\
        </div>");
        }
      }
    })
  }
</script>